"""
API layer.

Aggregates every feature app's URLconf under the ``/api/`` prefix and exposes
Swagger/OpenAPI documentation generated by drf-spectacular.

Routing map
-----------
/api/auth/          -> cph_app.urls       (register, login, logout, refresh, me, ...)
/api/consultants/   -> consultants.urls
/api/appointments/  -> appointments.urls
/api/blogs/         -> blogs.urls
/api/assessments/   -> (stub app, not wired yet)
/api/schema/        -> OpenAPI schema
/api/docs/          -> Swagger UI
/api/redoc/         -> ReDoc
"""