# Generated by Django 6.0.5 on 2026-08-08 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('stress', 'Stress'), ('anxiety', 'Anxiety'), ('depression', 'Depression'), ('burnout', 'Burnout'), ('sleep', 'Sleep'), ('wellbeing', 'Wellbeing'), ('adhd', 'ADHD'), ('social', 'Social')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
