# Generated by Django 6.0.5 on 2026-06-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0004_alter_consultant_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultantavailability',
            options={'ordering': ['day', 'start_time']},
        ),
        migrations.AddField(
            model_name='consultantavailability',
            name='session_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
