# Generated by Django 6.0.5 on 2026-08-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0005_alter_consultantavailability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
