# Generated by Django 6.0.5 on 2026-06-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_alter_consultant_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='consultants/'),
        ),
    ]
