# Generated by Django 6.0.5 on 2026-05-19 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cph_app', '0002_studentinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
