# Generated by Django 6.0.5 on 2026-06-28 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cph_app', '0006_alter_user_full_name_alter_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
