# Generated by Django 6.0.5 on 2026-05-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cph_app', '0004_studentinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='photo',
            new_name='photos',
        ),
    ]
