# Generated by Django 6.0.5 on 2026-05-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cph_app', '0005_rename_photo_studentinfo_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
